name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Stop service
        run: killall screen

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          REMOTE_HOST: ${{secrets.HOST_DNS}}
          REMOTE_USER: ${{secrets.USERNAME}}
          TARGET: ${{secrets.TARGET_DIR}}

      - name: Install requirements
        run: pip install -r ${{secrets.TARGET_DIR}}/requirements.txt

      - name: Rerun service
        run: screen -d -m sh ${{secrets.TARGET_DIR}}/run_server.sh
